#!/usr/bin/env bash

source ./lib/dot.sh

link_dotfiles() {
  link "git/gitattribute"
  link "git/gitconfig"
  link "git/gitignore"
  link "shell/curlrc"
  link "shell/inputrc"
  link "shell/wgetrc"
}

install_mac_tools() {
  brew_tap "homebrew/dupes"

  brew_install "grep"
  brew_install "openssh"
  brew_install "git"
  brew_install "ruby"
  brew_install "tig"
  brew_install "tree"
  brew_install "wget"
}

install_mac_apps() {
  brew_tap "caskroom/cask"
  brew_tap "caskroom/fonts"
  brew_tap "caskroom/versions"

  brew_install "brew-cask"

  cask_install "iterm2"
  cask_install "google-chrome"
  cask_install "spectacle"
  cask_install "sublime-text3"
}


defs() {
  group "Link dotfiles" link_dotfiles

  if is_mac?; then
    group "Install tools" install_mac_tools
    group "Install applications" install_mac_apps
  fi
}

dot_run defs
