#!/usr/bin/env bash

main() {
  ask_for_sudo

  e_header "Link dotfiles"
  e_ask "Continue"

  if answer_is_yes; then
    link "git/gitattribute"
    link "git/gitconfig"
    link "git/gitignore"
    link "shell/curlrc"
    link "shell/inputrc"
    link "shell/wgetrc"
  fi

  e_header "Install applications"
  e_ask "Continue"

  if answer_is_yes; then
    # OS X
    if is_osx; then
      install_xcode
      install_brew

      brew_tap "homebrew/dupes"
      brew_tap "caskroom/cask"
      brew_tap "caskroom/fonts"
      brew_tap "caskroom/versions"

      brew_install "brew-cask"
      brew_install "grep"
      brew_install "openssh"
      brew_install "git"
      brew_install "ruby"
      brew_install "tig"
      brew_install "tree"
      brew_install "wget" "--with-iri"

      brew_cask "google-chrome"
      brew_cask "spectacle"
      brew_cask "sublime-text3"
    fi

    # Debian / Ubuntu
    if is_debian; then
      package_install "tig"
      package_install "tree"
    fi
  fi

  printf "\n"
}

readonly DOTFILES_DIRECTORY=$(cd "$(dirname "$0")" && pwd)

source ./lib/core.sh
source ./lib/util.sh

if is_osx; then
  source ./lib/osx/brew.sh
  source ./lib/osx/xcode.sh
elif is_debian; then
  source ./lib/deb.sh
else
  e_error "This script is intended only for OS X and Debian"
  exit 1
fi

main "$@"
