#!/usr/bin/env bash

# Install Homebrew
if ! [ $(which brew) ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  brew update
  brew upgrade
  brew cleanup
fi
